# ZenDNS Configuration File
# Place at ~/.config/zendns/config.toml

# Multiple blocklist sources (URLs or local files)
blocklist_sources = [
    "https://someonewhocares.org/hosts/zero/hosts",
    "https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/adservers.txt",
    "/etc/zendns/custom_blocklist.txt"
]

# Network configuration
listen_addr = "127.0.0.1:53"    # UDP DNS server
dot_listen_addr = "127.0.0.1:853"  # DNS-over-TLS server
doh_listen_addr = "127.0.0.1:8443" # DNS-over-HTTPS server
upstream_addr = "1.1.1.1:53"

# TLS configuration for DoT/DoH (required if enabling these protocols)
tls_cert = "/etc/zendns/cert.pem"
tls_key = "/etc/zendns/key.pem"

# Protocol configuration (all optional, defaults shown)
enable_udp = true   # Fast, unencrypted DNS
enable_dot = false  # DNS-over-TLS (requires tls_cert/tls_key)
enable_doh = false  # DNS-over-HTTPS (requires tls_cert/tls_key)